[tasks.build_win64]
command = "cargo"
args = ["build", "--release"]

[tasks.copy_dll]
command = "cp"
args = ["target/release/gameplay.dll", "../ue5/Plugins/oz_lib/ThirdParty/Win64/gameplay.dll"]

[tasks.ue5]
dependencies = ["build_win64", "copy_dll"]

[tasks.build_wasm]
command = "cargo"
args = ["build", "--target", "wasm32v1-none", "--release"]

[tasks.copy_wasm]
command = "cp"
args = ["target/wasm32v1-none/release/gameplay.wasm", "../minigame/wasm/gameplay.wasm"]

[tasks.minigame]
dependencies = ["build_wasm", "copy_wasm"]


[tasks.schema]
command = "flatc"
args = ["--rust", "-o", "./src/schema", "schema/math.fbs", "schema/render_data.fbs"]
