# ================================= env declaration ================================= #
[env]
TARGET = {value = "x86_64-unknown-linux-gnu"}
RELEASE_PLATFORM = "pc"

[env.pc]
TARGET = "wasm32-unknown-unknown"
RELEASE_PLATFORM = "pc"

[env.mobile]
TARGET = "wasm32v1-none"
RELEASE_PLATFORM = "mobile"

[env.windows]
TARGET = "wasm32-unknown-unknown"
RELEASE_PLATFORM = "pc"
WAMRC_CMD = "wamrc.exe"

[env.linux]
TARGET = "wasm32-unknown-unknown"
RELEASE_PLATFORM = "pc"
WAMRC_CMD = "wamrc"

# =================================================================================== #

# ================================= task declaration ================================ #

[tasks.build_wasm]
command = "cargo"
args = ["build", "--target", "${TARGET}", "--release"]

[tasks.build_lib]
command = "cargo"
args = ["build", "--release"]

[tasks.build_aot]
command = "${WAMRC_CMD}"
args = ["--target=x86_64", "--size-level=1", "-o", "target/${TARGET}/release/gameplay.aot", "target/${TARGET}/release/gameplay.wasm"]

[tasks.cp_wasm]
script = "mkdir -p target/${RELEASE_PLATFORM}/release && cp target/${TARGET}/release/gameplay.wasm target/${RELEASE_PLATFORM}/release"

[tasks.cp_aot]
script = "mkdir -p target/${RELEASE_PLATFORM}/release && cp target/${TARGET}/release/gameplay.aot target/${RELEASE_PLATFORM}/release"

[tasks.schema_rust]
command = "flatc"
args = ["--rust", "-o", "src/schema", "schema/math.fbs", "schema/render_data.fbs", "schema/input_data.fbs"]

[tasks.schema_cpp]
command = "flatc"
args = ["--cpp", "-o", "../ue5/Plugins/oz_lib/Source/rust_lib/Public", "schema/math.fbs", "schema/render_data.fbs", "schema/input_data.fbs"]

# =================================================================================== #

# ============================== make task declaration ============================== #

# cargo make schema
[tasks.schema]
dependencies = ["schema_rust", "schema_cpp"]

# cargo make --profile pc wasm
# cargo make --profile mobile wasm
[tasks.wasm]
dependencies = ["build_wasm", "cp_wasm"]

# cargo make --profile windows aot
# cargo make --profile linux aot
[tasks.aot]
dependencies = ["build_wasm", "build_aot", "cp_wasm", "cp_aot"]

# cargo make lib
[tasks.lib]
dependencies = ["build_lib"]

# =================================================================================== #